### ISSUE TITLE
TrackPoint move speed in x1 carbon 2015

### ISSUE THREAD

**Issue by transtone** [tluck/OS-X-Voodoo-PS2-Controller#1]
jcsnider says in this commit:

https://github.com/jcsnider/OS-X-Voodoo-PS2-Controller/commit/b619ccce256797c92c8fd767e55f10763ee6e0a4

```
 X1 Carbon Compatibility Mods

Updated the project to run on OS X 10.9 SDK, it is working in the
latest Xcode.

Modified PS2Trackpad-Info.plist and set the default MouseMultiplierX/Y
and MouseScrollMultiplierX/Y to 1 in order to fix the super fast,
uncontrollable TrackPoint movement.

Finally I modified SynapticsTouchPad.cpp/.h to look for X1 Carbon
TrackPoint dedicated button packets to keep track of when the
left/right/middle buttons are clicked. Afterwards I inject the
dedicated button state into the following packet handler calls until
the buttons are released.
```

I change these lines in 1.8.24e's `plugins-->VoodooPS2Trackpad.kext-->Contents-->info.plist`  

https://github.com/tluck/OS-X-Voodoo-PS2-Controller/blob/master/VoodooPS2Trackpad/VoodooPS2Trackpad-Info.plist#L265-L272

to 

```
	<key>MouseMultiplierX</key>
					<integer>2</integer>
					<key>MouseMultiplierY</key>
					<integer>2</integer>
					<key>MouseScrollMultiplierX</key>
					<integer>1</integer>
					<key>MouseScrollMultiplierY</key>
					<integer>1</integer>
<key>
```
and it works!

but it not work in 1.8.24g.

**Comment by tluck** [comment]
ok, interesting. so version "e" works - with the above modifiers to slow things down? 

when you say "but it not work in 1.8.24g" - does that meaning nothing for TrackPoint or just the scrolling with TrackPoint?

**Comment by transtone** [comment]
I'm using `macos sierra 10.12.1`

above settings can slow the TrackPoint move speed.

in 1.8.24g, when I try to change the settings, the TrackPoint can't use, can't move. 
if I use 1.8.24g with no change, TrackPoint can move, but super fast.

I try to build kext from the source with Xcode, but the kext I built can't use: keybord, trackpad, trackpoint non function at all.

**Comment by tluck** [comment]
well yes the default settings are not good for the ClickPad/TrackPoint. thats why i created the LENOVO/T460 settings in the Info.plist.

so if 1.8.24g works as is from the zip file, but when you modified the Info.plist the kext did not work. so it seems the Info.plist was incorrectly modified. or the kext was not rebuilt properly? wrong perms?

**Comment by transtone** [comment]
sorry, I change the wrong section so it not work. it works good now with 1.8.24g . 

thank you very much!

the only thing left to solve is brightness and sound control with Fn + f2/f3... keys.

I delete the `./build` dir every time I build the kext. 
It just show me `build success` and there is no error message.
I don't know how to debug it.

**Comment by transtone** [comment]
some time works. but most of time not.
when reboot the system, if tracopoint worked on the login screen, it works fine anywhere; if not, it can't move anywhere.
