### ISSUE TITLE
Support ThinkPad E550?

### ISSUE THREAD

**Issue by CraKeyBoy** [tluck/OS-X-Voodoo-PS2-Controller#10]
Hello tluck. Does this kext suppot ThinkPad E550 ?  I can test this kext.

**Comment by tluck** [comment]
i have no idea if it will work or not. so sure - test it. it certainly looks like the same clickpad + buttons as on the t460

**Comment by javmain** [comment]
Do I need use SSDT-PS2K-XXX.dsl ?  And I don't konw how use this patch.

**Comment by CraKeyBoy** [comment]
Oh my God. 
Trackpoint work well. But press  middle button and trackpoint not scroll at web page or other program.
TouchPand only one finger work. no scroll, no three fringer.
And now I use this kext. https://github.com/DrHurt/OS-X-ALPS-DRIVER. It  work well.

**Comment by tluck** [comment]
it seems you have ALPS and not Synaptics - my fork only supports Synaptics.
