### ISSUE TITLE
X1C issues

### ISSUE THREAD

**Issue by axm2** [tluck/OS-X-Voodoo-PS2-Controller#11]
Hi, I've been using this kext on my x1c hackintosh for a while now and it has worked perfectly, thank you very much for maintaining and updating it. However sometimes the trackpoint doesn't work at all on boot, the trackpad and buttons work fine, but the trackpoint will just stay in the top left corner. I have to reboot a couple of times to have it work again, and it happens seemingly random. I'd like to troubleshoot but I'm not really sure how I would be able to.

**Comment by tluck** [comment]
are you using the latest version which forces passthru? this may help.

**Comment by axm2** [comment]
yes, I'm using 1.8.28a

**Comment by transtone** [comment]
It's a known bug since 10.12: 
https://github.com/tluck/OS-X-Voodoo-PS2-Controller/issues/5

https://github.com/tluck/OS-X-Voodoo-PS2-Controller/issues/9

I just reboot many times to have a good luck.
