### ISSUE TITLE
Kext for Trackpad of T450

### ISSUE THREAD

**Issue by PavlovMD** [tluck/OS-X-Voodoo-PS2-Controller#17]
Hi! I find your VoodooPS2Controller.kext for touchpad of T450 on tonymacx86 [here](https://www.tonymacx86.com/attachments/tluck-voodoops2controller-zip.302222/)
It's work wrong with macOS 10.15. Do you have optimized version this kext for 10.15? :)

It's very good kext for my T440p with trackpad of T450. But prefpanel don't view, trackpoint wrong moved cursor (arrow). 3-fingers swipes don't work(
Physical buttons worked very good. :-)
 
P.S. I'm sorry for my bad english.

**Comment by tluck** [comment]
Sorry - i stopped working on this about 3 years ago - I dont have a T460 to test anymore.

 it looks like there is new/better version that has most of my code implemented for Clickpads.

https://github.com/acidanthera/VoodooPS2

**Comment by PavlovMD** [comment]
> it looks like there is new/better version that has most of my code implemented for Clickpads.

No, with this new kext don't work trackpoint and physical buttons((

**Comment by PavlovMD** [comment]
Maybe you have source code of your old the best kext?

**Comment by tluck** [comment]
well - yeah. thats what this github contains - last source code. But i stopped updating my kext when RehabMan merged my code back into his version.  you should try RehabMan's version 1.9.x which supports buttons.

**Comment by PavlovMD** [comment]
So, Rehabman's kext... worked so so: all physical buttons worked as right click button and context menu hide after... dropped button. Trackpoint worked so so... ,but! prefpanel fine :-) 

Maybe you can send me source code of your kext? So maybe acidantera will be can see it's code...
