### ISSUE TITLE
TrackPoint not work

### ISSUE THREAD

**Issue by transtone** [tluck/OS-X-Voodoo-PS2-Controller#5]
when restart the Serria, if trackpoint worked in login screen, it works fine. if not, it never work! there almost 70% not work when restart my x1c-2015. trackpad and keyboard works.

with RehabMan-Voodoo, trackpoint works, but three button not. 

this is why I stick in 10.11 . but yesterday I can't login app store in 10.11, but the app store works fine in 10.12, I face the problem again.

**Comment by tluck** [comment]
i see the same thing on my T420 - sometimes trackpoint doesn't work when it boots. a sleep/wake will fix it. the same kext always works on my T460 from boot without issue.  i have no idea how to fix this random issue. note: this kext is forked from RehabMan's voodooPS2 - so essentially is the same kext.

**Comment by transtone** [comment]
In my laptop, a sleep/wake can't fix it.

**Comment by tluck** [comment]
maybe try this:

run:
`sudo kextunload -p /Library/Extensions/VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Trackpad.kext
`

then put to sleep and wake it 
then run:

`sudo kextload /Library/Extensions/VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Trackpad.kext`

**Comment by transtone** [comment]
There isn't a `VoodooPS2Controller.kext` diractory in /L/E/ . I always put the kext to clover's EFI/CLOVER/kexts/10.12/

If i put the kext to /L/E/, the keyboard can't use.

**Comment by tluck** [comment]
? i have all my custom kexts in /L/E  - but ok.
... but the point of this was to see if reloading the kext after wake would get the Trackpoint working for you.

**Comment by tluck** [comment]
Try the latest code - it fixes no TrackPoint on startup

**Comment by transtone** [comment]
I tried the latest 2 versions. but it not work in my x1c.

**Comment by tluck** [comment]
sorry to hear you are still having troubles.

**Comment by joshuaseltzer** [comment]
@tluck I'm having these same issues too with my T440s.  I used your kext since the trackpoint works great when it does load, but a lot of times it does not seem to load properly.  I also ordered a T450s trackpad to replace with the crappy T440s trackpad that comes by default.

Did you ever find a solution to it not loading properly?

**Comment by tluck** [comment]
maybe. i don't have a T460 anymore. but on my T420, with the recent change to force passthru, it always works. before it was like 50% chance.

**Comment by joshuaseltzer** [comment]
@tluck any suggestions on anything I could try to get it working?

The kext from this thread:
https://www.tonymacx86.com/threads/guide-2015-x1-carbon-yosemite.162391/
Always worked perfect for me on El Capitan with the normal trackpad. The track point always loaded.

**Comment by tluck** [comment]
so are you saying the latest code posted here is having problems?

at one point, I did look at jcsnider's code which should be very similar to this branch. does his version work?

**Comment by CoBrA2168** [comment]
Yeah, the latest code here compiled into a kext doesn't seem to want to load the track point most of the time. I downloaded a compiled kext here:

**Comment by joshuaseltzer** [comment]
Yeah, I'm using the latest compiled code from this repo. It was actually posted pre compiled attached a comment on this page:
https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-t440p.233282/page-3

But I do have Xcode on my Sierra machine so I suppose I could compile it myself and mess with the code.

The jcsnider code used to work 100% of the time on El Capitan but I believe I need a newer version of the kext for Sierra support.  Plus it was a very old version of the kext, so it was nice to use the latest one.

One thing I noticed is that even though the track point won't move, it does make the trackpad stop moving if I touch it. So move trackpad, then move track point = mouse stops so it's definitely recognized, just not moving anymore.
