### ISSUE TITLE
Karabiner-Elements can't recognize Fn key

### ISSUE THREAD

**Issue by transtone** [tluck/OS-X-Voodoo-PS2-Controller#6]
I don't kown it's `Karabiner-Elements`'s bug or keyboard driver's bug.

**Comment by jakibaki** [comment]
Afaik the fn keys are handled by the bios and then just send the special keys to the os as if they were pressed directly.

**Comment by tluck** [comment]
i am no expert here but with VoodooPS2, one can (re)map that the FN keys send when pressed. i dont know much about Karabiner? i did this awhile back for El Cap - but i quit using it. for example i wanted to match my Apple magic BT keyboard for the FN keys - in this case FN 6 is mapped to nothing.

					<key>T420-Options-not-used-for-Sierra</key>
					<dict>
						<key>Custom ADB Map</key>
						<array>
							<string>e01e=4d;previous</string>
							<string>e045=42;next</string>
						</array>
						<key>Custom PS2 Map</key>
						<array>
							<string>e01e=e037;Map tp disable to f8</string>
							<string>e037=e01e;Prevent PrntScr from triggering tp disable</string>
						</array>
						<key>Function Keys Special</key>
						<array>
							<string>;The following 12 items map fkeys to Fn+fkeys</string>
							<string>3b=e012; F1  - Brightness Down</string>
							<string>3c=e017; F2  - Brightness Up</string>
							<string>3d=e00a; F3  - Mission Control (app select)</string>
							<string>3e=e009; F4  - Launchpad</string>
							<string>3f=0;    F5  - nothing</string>
							<string>40=0;    F6  - nothing</string>
							<string>41=e06e; F7  - Video Mirror</string>
							<string>42=e037; F8  - TP on/off</string>
							<string>43=0;    F9  - nothing</string>
							<string>44=e020; F10 - Volume Mute</string>
							<string>57=e02e; F11 - Volume Up</string>
							<string>58=e030; F12 - Volume Up</string>
							<string>46=e022; ScrLck - iTunes - play/pause</string>
						</array>
						<key>Function Keys Standard</key>
						<array>
							<string>;The following 12 items map Fn+fkeys to Fn+fkeys</string>
							<string>e05f=e05f</string>
							<string>e012=e012</string>
							<string>e017=e017</string>
							<string>e06e=e06e</string>
							<string>e00a=e00a</string>
							<string>e009=e009</string>
							<string>e020=e020</string>
							<string>e02e=e02e</string>
							<string>e030=e030</string>
							<string>e010=e010</string>
							<string>e022=e022</string>
							<string>e019=e019</string>
							<string>;The following 12 items map fkeys to fkeys</string>
							<string>3b=3b</string>
							<string>3c=3c</string>
							<string>3d=3d</string>
							<string>3e=3e</string>
							<string>3f=3f</string>
							<string>40=40</string>
							<string>41=41</string>
							<string>42=42</string>
							<string>43=43</string>
							<string>44=44</string>
							<string>57=57</string>
							<string>58=58</string>
						</array>
					</dict>
