### ISSUE TITLE
TrackPoint Jumpiness (again)

### ISSUE THREAD

**Issue by cfis** [tluck/OS-X-Voodoo-PS2-Controller#7]
Tried to adopt this version of the kext again on a T450s.  But I still have the problem where my  trackpoint will jump 5 to 20 pixels on each movement - so its quite jerky.

I figured it was the mouseMultiplierX/Y settings which default to 20 (I personally like them at 1 or maybe 2).  But changning the plist made no difference so I just commented out the code in the extension and ran using that.  No difference.

Any ideas outside of the MultiplierX/Y settings that could cause this?

**Comment by tluck** [comment]
strange no diff with a setting change?
have you added properties/identifiers for the T450 in the PS2K device to use the non-default settings?
note: i disable dynamicEWMode on my T420 and T460. 
but have different settings depending on the model. resolution, multiplier, divisor have the most effect. as you can see what i set for ClickPad or TrackPad.  which Plugin kext is being used? remove PS2Mouse to make sure that is not in the picture.
