### ISSUE TITLE
trackpoint+physical buttons seen as mouse, and trackpad seen as trackpad.

### ISSUE THREAD

**Issue by nouatzi** [tluck/OS-X-Voodoo-PS2-Controller#9]
Hi, it's not really an issue, more like questions.
If I understand right, ps2trackpad kext takes care of both trackpad and trackpoint(+buttons).
Do you think it's possible to make the ps2mouse kext takes care of the trackpoint(+buttons) device,
 and the ps2trackpad kext takes care of the trackpad device?
When the trackpad is disabled in the BIOS, ps2mouse kext naturally takes over to handle the trackpoint(+buttons). And it's doing it pretty well.
it seems to be around the personalities matching process, I'm still trying to figure it out...
By the way, I wonder, there is 2 devices listed in the DSDT: PS2K(or KBD for me: x230) and MOU. So how does that work between the physical keyboard, the physical trackpoint and the physical trackpad?

**Comment by kenthinson** [comment]
by the trackball I think you mean the trackpoint? I would also be interested in this. as the trackpoint does not track smoothly when using both the touchpad and trackpoint enabled on the x230. but if I disable the trackpad the trackpoint works great! I've been trying to figure it out in my spare time but I don't have much of that. maybe @tluck can give me a hit where I should look to patch this.

**Comment by nouatzi** [comment]
The thing is, with the Thinkpad X230, 80% of the time, the trackpad and trackpoint work well. 
But sometimes, on a fresh boot (or reboot), the trackpoint (and its 3 buttons) doesn't work. 
I've to reload VoodooPS2Trackpad.kext in order for it to work again.
So, I've investigated this a bit, and it seems that the trackpoint is seen as a guest device, also called pass-through device, or pass-through capability. 
So in file VoodooPS2SynapticsTouchPad.cpp:
`void ApplePS2SynapticsTouchPad::queryCapabilities() { }`
For this to work, it needs both guest present and pass through capability:
`passthru = passthru1 & passthru2;`
But sometimes, for some unknown reason (for me), passthru1 (guest present) stays at 0. Which means passthru stays at 0 too.
So in order to bypass this problem, I simply add:
`passthru = true;`
to force passthru value.
Maybe there is a better way to do this, like wait a bit (sleep), and test passthru1 again, but I don't know how to do this...

And of course, don't forget, in the beginning of the source code file:
`#define FULL_HW_RESET`
It's needed, and already mentioned by tluck in some previous post.
I hope this helps those with Thinkpad X230.

**Comment by tsromana** [comment]
@nouatzi hi would you be able to share your kext file, I have been trying to fix out all the issues, now everything in x230 seems to be working only except the usual tracepoint and button issue on reboot and running audio using voodoo

**Comment by nouatzi** [comment]
All right, try [this](https://github.com/nouatzi/Voodoo-PS2-Controller):, and tell me how it goes.
For audio, I use [CodecCommander](https://github.com/RehabMan/EAPD-Codec-Commander) and [cloverHDA / Laptop / ALC269VC_v1.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12). And It works well. For cloverHDA, don't forget to follow the README.txt.
Also, from RehabMan too, [USB Inject All](https://github.com/RehabMan/OS-X-USB-Inject-All) helps with some other issues.

**Comment by tsromana** [comment]
@nouatzi thanks a lot will try this and will update you if this fixes the issue, as well as will try to create a good guide for x230 as the ones atm all guides are lacking in detailing some important aspects of the process :)

**Comment by nouatzi** [comment]
Good idea, I will take a look at your guide. ;)

**Comment by tsromana** [comment]
@nouatzi btw did you install the voodops2daemon too? I had a look at the wifi rebranding to intel, this way the software will not recognize the wifi card and we will need to recompile the software with the intel product ids to make it recognize again if we need to change something as well as will render the card useless on other ones, the atheros wifi adapter the 9285 already is whitelisted in the bios, so the best option is to rebrand it with the Lenovo substem id leaving the product id as default, there also seem to be card present on eBay which are already compatible without any rebranding whatsoever. I will detail this more in the guide.

**Comment by tsromana** [comment]
you are genius your custom kexts work awesome, no issues whatsoever working awesome in some reboot tests I have done, will update if I find any issue, will also update the audio in a bit, but I read somewhere you wrote that there is a issue something on sleep right.

**Comment by tluck** [comment]
cool. i changed 2 variables in the source - set skippassthru to true (which just was code to figure out passthru) and then set passthru to true.

**Comment by nouatzi** [comment]
Yes, I did install voodoops2daemon, I've just added it into the zip.
For the wifi rebranding, I think you're right, I may only need to change the subsystem id.
In a few days, I will try to flash the BIOS to completely unlock it. In order to use other cards. I'll tell you how it goes.
For the audio, well, it seems to work now, even after sleep/wake.

**Comment by tsromana** [comment]
thanks for all your help, could you please name the dsdt patches you
applied, as i an trying to collect everything together. after more playing
i found that there is sleep issues which i think are linked with some
missing DSDT patch. as far as audio its a bit complicated atm so will try
it in few days and will release a intial guide in few days as well.
hopefully the guide could help someone make it rock solid, so that theres
no need for digging around. again thanks for your help.

**Comment by nouatzi** [comment]
there should be the kext, plus a config.plist, and the DSDT patch in the README.txt inside the [ALC269VC_v1.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/raw/master/Laptop/ALC269VC_v1.zip)

**Comment by tsromana** [comment]
oh i thought its a bit more complicated didnt checked inside the zip. will
surely try it tomorrow. also i guess the sleep issue is with usb 3 instant
wake, do you know what patches you used for that ?

**Comment by nouatzi** [comment]
Unfortunately I didn't keep track on the DSDT patches I applied. I know I follow some of [Bizzaro guide](https://github.com/Bizzaro/x230-osx), and some of [RehabMan's](https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/).
So here is [my original DSDT, the patched DSDT, and the diff](https://github.com/nouatzi/DSDT)

**Comment by tsromana** [comment]
thanks a ton, that will help alot with the collection of all the patches.
